// Java file generated automatically from `jobpdo.fzdl'.
// $Timestamp: 2019-07-21 17:27:30
// DO NOT EDIT THIS FILE UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING.
//
package gtcloud.jobman.core.pdo;

import platon.ByteStream;
import platon.DefreezeException;
import platon.Freezable;
import platon.FreezerJSON;
import platon.FreezeException;
import platon.JsonNode;
import platon.Message;

public class JobStatusDO extends Message implements FreezerJSON
{
    public static final int FIELD_ID_JOBID = 0;
    public static final int FIELD_ID_JOBCATEGORY = 1;
    public static final int FIELD_ID_JOBCAPTION = 2;
    public static final int FIELD_ID_TOTALWORKLOAD = 3;
    public static final int FIELD_ID_STATUSCODE = 4;
    public static final int FIELD_ID_STATUSMESSAGE = 5;
    public static final int FIELD_ID_COMPLETEDWORKLOAD = 6;
    public static final int FIELD_ID_OPTIONS = 7;
    public static final int FIELD_ID_JOBEPOCH = 8;

    private String jobId = null;
    private String jobCategory = null;
    private String jobCaption = null;
    private double totalWorkload = 0;
    private int statusCode = 0;
    private String statusMessage = null;
    private double completedWorkload = 0;
    private platon.PropSet options = null;
    private long jobEpoch = 0;

    public JobStatusDO() {
        addField(FIELD_ID_JOBID);
        addField(FIELD_ID_JOBCATEGORY);
        addField(FIELD_ID_JOBCAPTION);
        addField(FIELD_ID_TOTALWORKLOAD);
        addField(FIELD_ID_STATUSCODE);
        addField(FIELD_ID_STATUSMESSAGE);
        addField(FIELD_ID_COMPLETEDWORKLOAD);
        if (this.options != null) {
            addField(FIELD_ID_OPTIONS);
        }
        addField(FIELD_ID_JOBEPOCH);
    }

    public JobStatusDO(JobStatusDO other) {
        this.copyFrom(other);
    }

    public String getJobId() {
        return this.jobId;
    }

    public void setJobId(String val) {
        this.jobId = val;
    }

    public String getJobCategory() {
        return this.jobCategory;
    }

    public void setJobCategory(String val) {
        this.jobCategory = val;
    }

    public String getJobCaption() {
        return this.jobCaption;
    }

    public void setJobCaption(String val) {
        this.jobCaption = val;
    }

    public double getTotalWorkload() {
        return this.totalWorkload;
    }

    public void setTotalWorkload(double val) {
        this.totalWorkload = val;
    }

    public int getStatusCode() {
        return this.statusCode;
    }

    public void setStatusCode(int val) {
        this.statusCode = val;
    }

    public String getStatusMessage() {
        return this.statusMessage;
    }

    public void setStatusMessage(String val) {
        this.statusMessage = val;
    }

    public double getCompletedWorkload() {
        return this.completedWorkload;
    }

    public void setCompletedWorkload(double val) {
        this.completedWorkload = val;
    }

    public platon.PropSet getOptions() {
        if (this.options == null) {
            this.options = new platon.PropSet();
            this.addField(FIELD_ID_OPTIONS);
        }
        return this.options;
    }

    public long getJobEpoch() {
        return this.jobEpoch;
    }

    public void setJobEpoch(long val) {
        this.jobEpoch = val;
    }


    // 从给定对象拷贝数据到当前对象
    @Override
    public void copyFrom(Freezable other) {
        super.copyFrom(other);
        JobStatusDO from = (JobStatusDO)other;
        this.jobId = from.jobId;
        this.jobCategory = from.jobCategory;
        this.jobCaption = from.jobCaption;
        this.totalWorkload = from.totalWorkload;
        this.statusCode = from.statusCode;
        this.statusMessage = from.statusMessage;
        this.completedWorkload = from.completedWorkload;
        if (this.options == null) {
            this.options = new platon.PropSet();
        }
        this.options.copyFrom(from.getOptions());
        this.jobEpoch = from.jobEpoch;
    }

    // 克隆当前对象。
    @Override
    public Freezable makeClone() {
        JobStatusDO o = new JobStatusDO();
        o.copyFrom(this);
        return o;
    }

    public void clear() {
        this.jobId = null;
        this.jobCategory = null;
        this.jobCaption = null;
        this.totalWorkload = 0;
        this.statusCode = 0;
        this.statusMessage = null;
        this.completedWorkload = 0;
        this.options = null;
        this.jobEpoch = 0;
        this.clearFields();
    }

    // 将当前对象打包进给定的字节流中。
    @Override
    public void freeze(ByteStream output) throws FreezeException {
        int[] cookie = new int[2];
        beginFreeze(output, cookie);

        if (hasField(FIELD_ID_JOBID)) {
            writeFieldString(output, FIELD_ID_JOBID, this.jobId);
        }

        if (hasField(FIELD_ID_JOBCATEGORY)) {
            writeFieldString(output, FIELD_ID_JOBCATEGORY, this.jobCategory);
        }

        if (hasField(FIELD_ID_JOBCAPTION)) {
            writeFieldString(output, FIELD_ID_JOBCAPTION, this.jobCaption);
        }

        if (hasField(FIELD_ID_TOTALWORKLOAD)) {
            writeFieldDouble(output, FIELD_ID_TOTALWORKLOAD, this.totalWorkload);
        }

        if (hasField(FIELD_ID_STATUSCODE)) {
            writeFieldInt(output, FIELD_ID_STATUSCODE, this.statusCode);
        }

        if (hasField(FIELD_ID_STATUSMESSAGE)) {
            writeFieldString(output, FIELD_ID_STATUSMESSAGE, this.statusMessage);
        }

        if (hasField(FIELD_ID_COMPLETEDWORKLOAD)) {
            writeFieldDouble(output, FIELD_ID_COMPLETEDWORKLOAD, this.completedWorkload);
        }

        if (hasField(FIELD_ID_OPTIONS)) {
            writeFieldObject(output, FIELD_ID_OPTIONS, this.options);
        }

        if (hasField(FIELD_ID_JOBEPOCH)) {
            writeFieldLong(output, FIELD_ID_JOBEPOCH, this.jobEpoch);
        }

        endFreeze(output, cookie);
    }

    // 从给定字节流中解包, 并将解包得到的数据覆盖到当前对象上。
    @Override
    public void defreeze(ByteStream input) throws DefreezeException {
        clear();

        int messageLen = beginDefreeze(input);
        int lastPos = input.read_pos();
        while (messageLen > 0) {
            int[] tuple = readTag(input);
            int tagType = tuple[0];
            int fieldId = tuple[1];

            boolean consumed = false;
            switch (fieldId) {
            case FIELD_ID_JOBID:
                if (tagType == TAG_TYPE_LEN_PREFIXED) {
                    this.jobId = readFieldString(input);
                    addField(FIELD_ID_JOBID);
                    consumed = true;
                }
                break;

            case FIELD_ID_JOBCATEGORY:
                if (tagType == TAG_TYPE_LEN_PREFIXED) {
                    this.jobCategory = readFieldString(input);
                    addField(FIELD_ID_JOBCATEGORY);
                    consumed = true;
                }
                break;

            case FIELD_ID_JOBCAPTION:
                if (tagType == TAG_TYPE_LEN_PREFIXED) {
                    this.jobCaption = readFieldString(input);
                    addField(FIELD_ID_JOBCAPTION);
                    consumed = true;
                }
                break;

            case FIELD_ID_TOTALWORKLOAD:
                if (tagType == TAG_TYPE_FIXED64) {
                    this.totalWorkload = readFieldDouble(input);
                    addField(FIELD_ID_TOTALWORKLOAD);
                    consumed = true;
                }
                break;

            case FIELD_ID_STATUSCODE:
                if (tagType == TAG_TYPE_VARINT32) {
                    this.statusCode = readFieldInt(input);
                    addField(FIELD_ID_STATUSCODE);
                    consumed = true;
                }
                break;

            case FIELD_ID_STATUSMESSAGE:
                if (tagType == TAG_TYPE_LEN_PREFIXED) {
                    this.statusMessage = readFieldString(input);
                    addField(FIELD_ID_STATUSMESSAGE);
                    consumed = true;
                }
                break;

            case FIELD_ID_COMPLETEDWORKLOAD:
                if (tagType == TAG_TYPE_FIXED64) {
                    this.completedWorkload = readFieldDouble(input);
                    addField(FIELD_ID_COMPLETEDWORKLOAD);
                    consumed = true;
                }
                break;

            case FIELD_ID_OPTIONS:
                if (tagType == TAG_TYPE_EMBEDDEDMSG) {
                    if (this.options == null) {
                        this.options = new platon.PropSet();
                    }
                    readFieldObject(input, this.options);
                    addField(FIELD_ID_OPTIONS);
                    consumed = true;
                }
                break;

            case FIELD_ID_JOBEPOCH:
                if (tagType == TAG_TYPE_FIXED64) {
                    this.jobEpoch = readFieldLong(input);
                    addField(FIELD_ID_JOBEPOCH);
                    consumed = true;
                }
                break;
            }

            if (!consumed) {
                // unknown field, ignore it
                discardBytes(input, tagType);
            }

            final int currentPos = input.read_pos();
            messageLen -= (currentPos - lastPos);
            lastPos = currentPos;
        }

        endDefreeze(input);
    }

    // 将当前消息打包成JSON树, 返回JSON树的指针
    @Override
    public JsonNode freezeToJSON() throws FreezeException {
        JsonNode thisNode = JsonNode.createJsonObject();

        if (hasField(FIELD_ID_JOBID) && this.jobId != null) {
            JsonNode val_c_jobId = new JsonNode(this.jobId);
            thisNode.put("jobId", val_c_jobId);
        }

        if (hasField(FIELD_ID_JOBCATEGORY) && this.jobCategory != null) {
            JsonNode val_c_jobCategory = new JsonNode(this.jobCategory);
            thisNode.put("jobCategory", val_c_jobCategory);
        }

        if (hasField(FIELD_ID_JOBCAPTION) && this.jobCaption != null) {
            JsonNode val_c_jobCaption = new JsonNode(this.jobCaption);
            thisNode.put("jobCaption", val_c_jobCaption);
        }

        if (hasField(FIELD_ID_TOTALWORKLOAD)) {
            JsonNode val_c_totalWorkload = new JsonNode(this.totalWorkload);
            thisNode.put("totalWorkload", val_c_totalWorkload);
        }

        if (hasField(FIELD_ID_STATUSCODE)) {
            JsonNode val_c_statusCode = new JsonNode(this.statusCode);
            thisNode.put("statusCode", val_c_statusCode);
        }

        if (hasField(FIELD_ID_STATUSMESSAGE) && this.statusMessage != null) {
            JsonNode val_c_statusMessage = new JsonNode(this.statusMessage);
            thisNode.put("statusMessage", val_c_statusMessage);
        }

        if (hasField(FIELD_ID_COMPLETEDWORKLOAD)) {
            JsonNode val_c_completedWorkload = new JsonNode(this.completedWorkload);
            thisNode.put("completedWorkload", val_c_completedWorkload);
        }

        if (hasField(FIELD_ID_OPTIONS) && this.options != null) {
            JsonNode val_c_options = this.options.freezeToJSON();
            thisNode.put("options", val_c_options);
        }

        if (hasField(FIELD_ID_JOBEPOCH)) {
            JsonNode val_c_jobEpoch = new JsonNode(this.jobEpoch);
            thisNode.put("jobEpoch", val_c_jobEpoch);
        }
        return thisNode;
    }

    // 从给定JSON树中解包, 并将解包得到的数据覆盖到当前消息上。
    @Override
    public void defreezeFromJSON(JsonNode inputJsonNode) throws DefreezeException {
        if (!inputJsonNode.isObject()) {
            throw new DefreezeException("input json is not object");
        }
        clear();

        JsonNode val_c_jobId = inputJsonNode.get("jobId");
        if (val_c_jobId != null && !val_c_jobId.isNull()) {
            this.jobId = val_c_jobId.asString();
            addField(FIELD_ID_JOBID);
        }

        JsonNode val_c_jobCategory = inputJsonNode.get("jobCategory");
        if (val_c_jobCategory != null && !val_c_jobCategory.isNull()) {
            this.jobCategory = val_c_jobCategory.asString();
            addField(FIELD_ID_JOBCATEGORY);
        }

        JsonNode val_c_jobCaption = inputJsonNode.get("jobCaption");
        if (val_c_jobCaption != null && !val_c_jobCaption.isNull()) {
            this.jobCaption = val_c_jobCaption.asString();
            addField(FIELD_ID_JOBCAPTION);
        }

        JsonNode val_c_totalWorkload = inputJsonNode.get("totalWorkload");
        if (val_c_totalWorkload != null && !val_c_totalWorkload.isNull()) {
            this.totalWorkload = val_c_totalWorkload.asDouble();
            addField(FIELD_ID_TOTALWORKLOAD);
        }

        JsonNode val_c_statusCode = inputJsonNode.get("statusCode");
        if (val_c_statusCode != null && !val_c_statusCode.isNull()) {
            this.statusCode = (int)val_c_statusCode.asInt64();
            addField(FIELD_ID_STATUSCODE);
        }

        JsonNode val_c_statusMessage = inputJsonNode.get("statusMessage");
        if (val_c_statusMessage != null && !val_c_statusMessage.isNull()) {
            this.statusMessage = val_c_statusMessage.asString();
            addField(FIELD_ID_STATUSMESSAGE);
        }

        JsonNode val_c_completedWorkload = inputJsonNode.get("completedWorkload");
        if (val_c_completedWorkload != null && !val_c_completedWorkload.isNull()) {
            this.completedWorkload = val_c_completedWorkload.asDouble();
            addField(FIELD_ID_COMPLETEDWORKLOAD);
        }

        JsonNode val_c_options = inputJsonNode.get("options");
        if (val_c_options != null && !val_c_options.isNull()) {
            this.getOptions().defreezeFromJSON(val_c_options);
            addField(FIELD_ID_OPTIONS);
        }

        JsonNode val_c_jobEpoch = inputJsonNode.get("jobEpoch");
        if (val_c_jobEpoch != null && !val_c_jobEpoch.isNull()) {
            this.jobEpoch = val_c_jobEpoch.asInt64();
            addField(FIELD_ID_JOBEPOCH);
        }
    }
}

