// Java file generated automatically from `schedpdo.fzdl'.
// $Timestamp: 2018-04-18 15:58:28
// DO NOT EDIT THIS FILE UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING.
//
package gtcloud.jobman.core.pdo;

public abstract class Phase
{
    public static final int PHASE_BEGIN = 100;

    public static final int PHASE_INPROGRESS = 101;

    public static final int PHASE_DONE = 102;
}

