// Java file generated automatically from `schedpdo.fzdl'.
// $Timestamp: 2019-07-12 19:46:05
// DO NOT EDIT THIS FILE UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING.
//
package gtcloud.jobman.core.pdo;

public abstract class StepTag
{
    public static final int BEGIN = 1;

    public static final int END = 2;
}

