// Java file generated automatically from `schedpdo.fzdl'.
// $Timestamp: 2019-08-12 11:56:32
// DO NOT EDIT THIS FILE UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING.
//
package gtcloud.jobman.core.pdo;

import platon.ByteStream;
import platon.DefreezeException;
import platon.Freezable;
import platon.FreezerJSON;
import platon.FreezeException;
import platon.JsonNode;
import platon.Message;

public class SubjobStatusDO extends Message implements FreezerJSON
{
    public static final int FIELD_ID_STATUSCODE = 0;
    public static final int FIELD_ID_STATUSMESSAGE = 1;
    public static final int FIELD_ID_COMPLETEDWORKLOAD = 2;
    public static final int FIELD_ID_PHASE = 3;
    public static final int FIELD_ID_OPTIONS = 4;
    public static final int FIELD_ID_STEPID = 5;
    public static final int FIELD_ID_STEPTAG = 6;

    private int statusCode = 0;
    private String statusMessage = null;
    private double completedWorkload = 0;
    private int phase = 0;
    private platon.PropSet options = null;
    private String stepId = null;
    private int stepTag = 0;

    public SubjobStatusDO() {
        addField(FIELD_ID_STATUSCODE);
        addField(FIELD_ID_STATUSMESSAGE);
        addField(FIELD_ID_COMPLETEDWORKLOAD);
        addField(FIELD_ID_PHASE);
        if (this.options != null) {
            addField(FIELD_ID_OPTIONS);
        }
        addField(FIELD_ID_STEPID);
        addField(FIELD_ID_STEPTAG);
    }

    public SubjobStatusDO(SubjobStatusDO other) {
        this.copyFrom(other);
    }

    public int getStatusCode() {
        return this.statusCode;
    }

    public void setStatusCode(int val) {
        this.statusCode = val;
    }

    public String getStatusMessage() {
        return this.statusMessage;
    }

    public void setStatusMessage(String val) {
        this.statusMessage = val;
    }

    public double getCompletedWorkload() {
        return this.completedWorkload;
    }

    public void setCompletedWorkload(double val) {
        this.completedWorkload = val;
    }

    public int getPhase() {
        return this.phase;
    }

    public void setPhase(int val) {
        this.phase = val;
    }

    public platon.PropSet getOptions() {
        if (this.options == null) {
            this.options = new platon.PropSet();
            this.addField(FIELD_ID_OPTIONS);
        }
        return this.options;
    }

    public String getStepId() {
        return this.stepId;
    }

    public void setStepId(String val) {
        this.stepId = val;
    }

    public int getStepTag() {
        return this.stepTag;
    }

    public void setStepTag(int val) {
        this.stepTag = val;
    }


    // 从给定对象拷贝数据到当前对象
    @Override
    public void copyFrom(Freezable other) {
        super.copyFrom(other);
        SubjobStatusDO from = (SubjobStatusDO)other;
        this.statusCode = from.statusCode;
        this.statusMessage = from.statusMessage;
        this.completedWorkload = from.completedWorkload;
        this.phase = from.phase;
        if (this.options == null) {
            this.options = new platon.PropSet();
        }
        this.options.copyFrom(from.getOptions());
        this.stepId = from.stepId;
        this.stepTag = from.stepTag;
    }

    // 克隆当前对象。
    @Override
    public Freezable makeClone() {
        SubjobStatusDO o = new SubjobStatusDO();
        o.copyFrom(this);
        return o;
    }

    public void clear() {
        this.statusCode = 0;
        this.statusMessage = null;
        this.completedWorkload = 0;
        this.phase = 0;
        this.options = null;
        this.stepId = null;
        this.stepTag = 0;
        this.clearFields();
    }

    // 将当前对象打包进给定的字节流中。
    @Override
    public void freeze(ByteStream output) throws FreezeException {
        int[] cookie = new int[2];
        beginFreeze(output, cookie);

        if (hasField(FIELD_ID_STATUSCODE)) {
            writeFieldInt(output, FIELD_ID_STATUSCODE, this.statusCode);
        }

        if (hasField(FIELD_ID_STATUSMESSAGE)) {
            writeFieldString(output, FIELD_ID_STATUSMESSAGE, this.statusMessage);
        }

        if (hasField(FIELD_ID_COMPLETEDWORKLOAD)) {
            writeFieldDouble(output, FIELD_ID_COMPLETEDWORKLOAD, this.completedWorkload);
        }

        if (hasField(FIELD_ID_PHASE)) {
            writeFieldInt(output, FIELD_ID_PHASE, this.phase);
        }

        if (hasField(FIELD_ID_OPTIONS)) {
            writeFieldObject(output, FIELD_ID_OPTIONS, this.options);
        }

        if (hasField(FIELD_ID_STEPID)) {
            writeFieldString(output, FIELD_ID_STEPID, this.stepId);
        }

        if (hasField(FIELD_ID_STEPTAG)) {
            writeFieldInt(output, FIELD_ID_STEPTAG, this.stepTag);
        }

        endFreeze(output, cookie);
    }

    // 从给定字节流中解包, 并将解包得到的数据覆盖到当前对象上。
    @Override
    public void defreeze(ByteStream input) throws DefreezeException {
        clear();

        int messageLen = beginDefreeze(input);
        int lastPos = input.read_pos();
        while (messageLen > 0) {
            int[] tuple = readTag(input);
            int tagType = tuple[0];
            int fieldId = tuple[1];

            boolean consumed = false;
            switch (fieldId) {
            case FIELD_ID_STATUSCODE:
                if (tagType == TAG_TYPE_VARINT32) {
                    this.statusCode = readFieldInt(input);
                    addField(FIELD_ID_STATUSCODE);
                    consumed = true;
                }
                break;

            case FIELD_ID_STATUSMESSAGE:
                if (tagType == TAG_TYPE_LEN_PREFIXED) {
                    this.statusMessage = readFieldString(input);
                    addField(FIELD_ID_STATUSMESSAGE);
                    consumed = true;
                }
                break;

            case FIELD_ID_COMPLETEDWORKLOAD:
                if (tagType == TAG_TYPE_FIXED64) {
                    this.completedWorkload = readFieldDouble(input);
                    addField(FIELD_ID_COMPLETEDWORKLOAD);
                    consumed = true;
                }
                break;

            case FIELD_ID_PHASE:
                if (tagType == TAG_TYPE_VARINT32) {
                    this.phase = readFieldInt(input);
                    addField(FIELD_ID_PHASE);
                    consumed = true;
                }
                break;

            case FIELD_ID_OPTIONS:
                if (tagType == TAG_TYPE_EMBEDDEDMSG) {
                    if (this.options == null) {
                        this.options = new platon.PropSet();
                    }
                    readFieldObject(input, this.options);
                    addField(FIELD_ID_OPTIONS);
                    consumed = true;
                }
                break;

            case FIELD_ID_STEPID:
                if (tagType == TAG_TYPE_LEN_PREFIXED) {
                    this.stepId = readFieldString(input);
                    addField(FIELD_ID_STEPID);
                    consumed = true;
                }
                break;

            case FIELD_ID_STEPTAG:
                if (tagType == TAG_TYPE_VARINT32) {
                    this.stepTag = readFieldInt(input);
                    addField(FIELD_ID_STEPTAG);
                    consumed = true;
                }
                break;
            }

            if (!consumed) {
                // unknown field, ignore it
                discardBytes(input, tagType);
            }

            final int currentPos = input.read_pos();
            messageLen -= (currentPos - lastPos);
            lastPos = currentPos;
        }

        endDefreeze(input);
    }

    // 将当前消息打包成JSON树, 返回JSON树的指针
    @Override
    public JsonNode freezeToJSON() throws FreezeException {
        JsonNode thisNode = JsonNode.createJsonObject();

        if (hasField(FIELD_ID_STATUSCODE)) {
            JsonNode val_c_statusCode = new JsonNode(this.statusCode);
            thisNode.put("statusCode", val_c_statusCode);
        }

        if (hasField(FIELD_ID_STATUSMESSAGE) && this.statusMessage != null) {
            JsonNode val_c_statusMessage = new JsonNode(this.statusMessage);
            thisNode.put("statusMessage", val_c_statusMessage);
        }

        if (hasField(FIELD_ID_COMPLETEDWORKLOAD)) {
            JsonNode val_c_completedWorkload = new JsonNode(this.completedWorkload);
            thisNode.put("completedWorkload", val_c_completedWorkload);
        }

        if (hasField(FIELD_ID_PHASE)) {
            JsonNode val_c_phase = new JsonNode(this.phase);
            thisNode.put("phase", val_c_phase);
        }

        if (hasField(FIELD_ID_OPTIONS) && this.options != null) {
            JsonNode val_c_options = this.options.freezeToJSON();
            thisNode.put("options", val_c_options);
        }

        if (hasField(FIELD_ID_STEPID) && this.stepId != null) {
            JsonNode val_c_stepId = new JsonNode(this.stepId);
            thisNode.put("stepId", val_c_stepId);
        }

        if (hasField(FIELD_ID_STEPTAG)) {
            JsonNode val_c_stepTag = new JsonNode(this.stepTag);
            thisNode.put("stepTag", val_c_stepTag);
        }
        return thisNode;
    }

    // 从给定JSON树中解包, 并将解包得到的数据覆盖到当前消息上。
    @Override
    public void defreezeFromJSON(JsonNode inputJsonNode) throws DefreezeException {
        if (!inputJsonNode.isObject()) {
            throw new DefreezeException("input json is not object");
        }
        clear();

        JsonNode val_c_statusCode = inputJsonNode.get("statusCode");
        if (val_c_statusCode != null && !val_c_statusCode.isNull()) {
            this.statusCode = (int)val_c_statusCode.asInt64();
            addField(FIELD_ID_STATUSCODE);
        }

        JsonNode val_c_statusMessage = inputJsonNode.get("statusMessage");
        if (val_c_statusMessage != null && !val_c_statusMessage.isNull()) {
            this.statusMessage = val_c_statusMessage.asString();
            addField(FIELD_ID_STATUSMESSAGE);
        }

        JsonNode val_c_completedWorkload = inputJsonNode.get("completedWorkload");
        if (val_c_completedWorkload != null && !val_c_completedWorkload.isNull()) {
            this.completedWorkload = val_c_completedWorkload.asDouble();
            addField(FIELD_ID_COMPLETEDWORKLOAD);
        }

        JsonNode val_c_phase = inputJsonNode.get("phase");
        if (val_c_phase != null && !val_c_phase.isNull()) {
            this.phase = (int)val_c_phase.asInt64();
            addField(FIELD_ID_PHASE);
        }

        JsonNode val_c_options = inputJsonNode.get("options");
        if (val_c_options != null && !val_c_options.isNull()) {
            this.getOptions().defreezeFromJSON(val_c_options);
            addField(FIELD_ID_OPTIONS);
        }

        JsonNode val_c_stepId = inputJsonNode.get("stepId");
        if (val_c_stepId != null && !val_c_stepId.isNull()) {
            this.stepId = val_c_stepId.asString();
            addField(FIELD_ID_STEPID);
        }

        JsonNode val_c_stepTag = inputJsonNode.get("stepTag");
        if (val_c_stepTag != null && !val_c_stepTag.isNull()) {
            this.stepTag = (int)val_c_stepTag.asInt64();
            addField(FIELD_ID_STEPTAG);
        }
    }
}

