// Java file generated automatically from `autogen.fzdl'.
// $Timestamp: 2018-11-28 18:08:43
// DO NOT EDIT THIS FILE UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING.
//
package gtcloud.common.cynosure.pdo;

import platon.ByteStream;
import platon.DefreezeException;
import platon.Freezable;
import platon.FreezerJSON;
import platon.FreezeException;
import platon.JsonNode;
import platon.Message;

public class AppInfoDO extends Message implements FreezerJSON
{
    public static final int FIELD_ID_SERVEREPOCH = 0;
    public static final int FIELD_ID_APPNAME = 1;
    public static final int FIELD_ID_SERVICEADDRESS = 2;
    public static final int FIELD_ID_PID = 3;
    public static final int FIELD_ID_PROBECOUNT = 4;
    public static final int FIELD_ID_SERVERCURRENTMILLIS = 5;
    public static final int FIELD_ID_LASTACTIVEMILLIS = 6;
    public static final int FIELD_ID_OPTIONS = 7;

    private long serverEpoch = 0;
    private String appName = null;
    private String serviceAddress = null;
    private int pid = 0;
    private long probeCount = 0;
    private long serverCurrentMillis = 0;
    private long lastActiveMillis = 0;
    private platon.PropSet options = null;

    public AppInfoDO() {
        addField(FIELD_ID_SERVEREPOCH);
        addField(FIELD_ID_APPNAME);
        addField(FIELD_ID_SERVICEADDRESS);
        addField(FIELD_ID_PID);
        addField(FIELD_ID_PROBECOUNT);
        addField(FIELD_ID_SERVERCURRENTMILLIS);
        addField(FIELD_ID_LASTACTIVEMILLIS);
        if (this.options != null) {
            addField(FIELD_ID_OPTIONS);
        }
    }

    public AppInfoDO(AppInfoDO other) {
        this.copyFrom(other);
    }

    public long getServerEpoch() {
        return this.serverEpoch;
    }

    public void setServerEpoch(long val) {
        this.serverEpoch = val;
    }

    public String getAppName() {
        return this.appName;
    }

    public void setAppName(String val) {
        this.appName = val;
    }

    public String getServiceAddress() {
        return this.serviceAddress;
    }

    public void setServiceAddress(String val) {
        this.serviceAddress = val;
    }

    public int getPid() {
        return this.pid;
    }

    public void setPid(int val) {
        this.pid = val;
    }

    public long getProbeCount() {
        return this.probeCount;
    }

    public void setProbeCount(long val) {
        this.probeCount = val;
    }

    public long getServerCurrentMillis() {
        return this.serverCurrentMillis;
    }

    public void setServerCurrentMillis(long val) {
        this.serverCurrentMillis = val;
    }

    public long getLastActiveMillis() {
        return this.lastActiveMillis;
    }

    public void setLastActiveMillis(long val) {
        this.lastActiveMillis = val;
    }

    public platon.PropSet getOptions() {
        if (this.options == null) {
            this.options = new platon.PropSet();
            this.addField(FIELD_ID_OPTIONS);
        }
        return this.options;
    }


    // 从给定对象拷贝数据到当前对象
    @Override
    public void copyFrom(Freezable other) {
        super.copyFrom(other);
        AppInfoDO from = (AppInfoDO)other;
        this.serverEpoch = from.serverEpoch;
        this.appName = from.appName;
        this.serviceAddress = from.serviceAddress;
        this.pid = from.pid;
        this.probeCount = from.probeCount;
        this.serverCurrentMillis = from.serverCurrentMillis;
        this.lastActiveMillis = from.lastActiveMillis;
        if (this.options == null) {
            this.options = new platon.PropSet();
        }
        this.options.copyFrom(from.getOptions());
    }

    // 克隆当前对象。
    @Override
    public Freezable makeClone() {
        AppInfoDO o = new AppInfoDO();
        o.copyFrom(this);
        return o;
    }

    public void clear() {
        this.serverEpoch = 0;
        this.appName = null;
        this.serviceAddress = null;
        this.pid = 0;
        this.probeCount = 0;
        this.serverCurrentMillis = 0;
        this.lastActiveMillis = 0;
        this.options = null;
        this.clearFields();
    }

    // 将当前对象打包进给定的字节流中。
    @Override
    public void freeze(ByteStream output) throws FreezeException {
        int[] cookie = new int[2];
        beginFreeze(output, cookie);

        if (hasField(FIELD_ID_SERVEREPOCH)) {
            writeFieldLong(output, FIELD_ID_SERVEREPOCH, this.serverEpoch);
        }

        if (hasField(FIELD_ID_APPNAME)) {
            writeFieldString(output, FIELD_ID_APPNAME, this.appName);
        }

        if (hasField(FIELD_ID_SERVICEADDRESS)) {
            writeFieldString(output, FIELD_ID_SERVICEADDRESS, this.serviceAddress);
        }

        if (hasField(FIELD_ID_PID)) {
            writeFieldInt(output, FIELD_ID_PID, this.pid);
        }

        if (hasField(FIELD_ID_PROBECOUNT)) {
            writeFieldLong(output, FIELD_ID_PROBECOUNT, this.probeCount);
        }

        if (hasField(FIELD_ID_SERVERCURRENTMILLIS)) {
            writeFieldLong(output, FIELD_ID_SERVERCURRENTMILLIS, this.serverCurrentMillis);
        }

        if (hasField(FIELD_ID_LASTACTIVEMILLIS)) {
            writeFieldLong(output, FIELD_ID_LASTACTIVEMILLIS, this.lastActiveMillis);
        }

        if (hasField(FIELD_ID_OPTIONS)) {
            writeFieldObject(output, FIELD_ID_OPTIONS, this.options);
        }

        endFreeze(output, cookie);
    }

    // 从给定字节流中解包, 并将解包得到的数据覆盖到当前对象上。
    @Override
    public void defreeze(ByteStream input) throws DefreezeException {
        clear();

        int messageLen = beginDefreeze(input);
        int lastPos = input.read_pos();
        while (messageLen > 0) {
            int[] tuple = readTag(input);
            int tagType = tuple[0];
            int fieldId = tuple[1];

            boolean consumed = false;
            switch (fieldId) {
            case FIELD_ID_SERVEREPOCH:
                if (tagType == TAG_TYPE_FIXED64) {
                    this.serverEpoch = readFieldLong(input);
                    addField(FIELD_ID_SERVEREPOCH);
                    consumed = true;
                }
                break;

            case FIELD_ID_APPNAME:
                if (tagType == TAG_TYPE_LEN_PREFIXED) {
                    this.appName = readFieldString(input);
                    addField(FIELD_ID_APPNAME);
                    consumed = true;
                }
                break;

            case FIELD_ID_SERVICEADDRESS:
                if (tagType == TAG_TYPE_LEN_PREFIXED) {
                    this.serviceAddress = readFieldString(input);
                    addField(FIELD_ID_SERVICEADDRESS);
                    consumed = true;
                }
                break;

            case FIELD_ID_PID:
                if (tagType == TAG_TYPE_VARINT32) {
                    this.pid = readFieldInt(input);
                    addField(FIELD_ID_PID);
                    consumed = true;
                }
                break;

            case FIELD_ID_PROBECOUNT:
                if (tagType == TAG_TYPE_FIXED64) {
                    this.probeCount = readFieldLong(input);
                    addField(FIELD_ID_PROBECOUNT);
                    consumed = true;
                }
                break;

            case FIELD_ID_SERVERCURRENTMILLIS:
                if (tagType == TAG_TYPE_FIXED64) {
                    this.serverCurrentMillis = readFieldLong(input);
                    addField(FIELD_ID_SERVERCURRENTMILLIS);
                    consumed = true;
                }
                break;

            case FIELD_ID_LASTACTIVEMILLIS:
                if (tagType == TAG_TYPE_FIXED64) {
                    this.lastActiveMillis = readFieldLong(input);
                    addField(FIELD_ID_LASTACTIVEMILLIS);
                    consumed = true;
                }
                break;

            case FIELD_ID_OPTIONS:
                if (tagType == TAG_TYPE_EMBEDDEDMSG) {
                    if (this.options == null) {
                        this.options = new platon.PropSet();
                    }
                    readFieldObject(input, this.options);
                    addField(FIELD_ID_OPTIONS);
                    consumed = true;
                }
                break;
            }

            if (!consumed) {
                // unknown field, ignore it
                discardBytes(input, tagType);
            }

            final int currentPos = input.read_pos();
            messageLen -= (currentPos - lastPos);
            lastPos = currentPos;
        }

        endDefreeze(input);
    }

    // 将当前消息打包成JSON树, 返回JSON树的指针
    @Override
    public JsonNode freezeToJSON() throws FreezeException {
        JsonNode thisNode = JsonNode.createJsonObject();

        if (hasField(FIELD_ID_SERVEREPOCH)) {
            JsonNode val_c_serverEpoch = new JsonNode(this.serverEpoch);
            thisNode.put("serverEpoch", val_c_serverEpoch);
        }

        if (hasField(FIELD_ID_APPNAME) && this.appName != null) {
            JsonNode val_c_appName = new JsonNode(this.appName);
            thisNode.put("appName", val_c_appName);
        }

        if (hasField(FIELD_ID_SERVICEADDRESS) && this.serviceAddress != null) {
            JsonNode val_c_serviceAddress = new JsonNode(this.serviceAddress);
            thisNode.put("serviceAddress", val_c_serviceAddress);
        }

        if (hasField(FIELD_ID_PID)) {
            JsonNode val_c_pid = new JsonNode(this.pid);
            thisNode.put("pid", val_c_pid);
        }

        if (hasField(FIELD_ID_PROBECOUNT)) {
            JsonNode val_c_probeCount = new JsonNode(this.probeCount);
            thisNode.put("probeCount", val_c_probeCount);
        }

        if (hasField(FIELD_ID_SERVERCURRENTMILLIS)) {
            JsonNode val_c_serverCurrentMillis = new JsonNode(this.serverCurrentMillis);
            thisNode.put("serverCurrentMillis", val_c_serverCurrentMillis);
        }

        if (hasField(FIELD_ID_LASTACTIVEMILLIS)) {
            JsonNode val_c_lastActiveMillis = new JsonNode(this.lastActiveMillis);
            thisNode.put("lastActiveMillis", val_c_lastActiveMillis);
        }

        if (hasField(FIELD_ID_OPTIONS) && this.options != null) {
            JsonNode val_c_options = this.options.freezeToJSON();
            thisNode.put("options", val_c_options);
        }
        return thisNode;
    }

    // 从给定JSON树中解包, 并将解包得到的数据覆盖到当前消息上。
    @Override
    public void defreezeFromJSON(JsonNode inputJsonNode) throws DefreezeException {
        if (!inputJsonNode.isObject()) {
            throw new DefreezeException("input json is not object");
        }
        clear();

        JsonNode val_c_serverEpoch = inputJsonNode.get("serverEpoch");
        if (val_c_serverEpoch != null && !val_c_serverEpoch.isNull()) {
            this.serverEpoch = val_c_serverEpoch.asInt64();
            addField(FIELD_ID_SERVEREPOCH);
        }

        JsonNode val_c_appName = inputJsonNode.get("appName");
        if (val_c_appName != null && !val_c_appName.isNull()) {
            this.appName = val_c_appName.asString();
            addField(FIELD_ID_APPNAME);
        }

        JsonNode val_c_serviceAddress = inputJsonNode.get("serviceAddress");
        if (val_c_serviceAddress != null && !val_c_serviceAddress.isNull()) {
            this.serviceAddress = val_c_serviceAddress.asString();
            addField(FIELD_ID_SERVICEADDRESS);
        }

        JsonNode val_c_pid = inputJsonNode.get("pid");
        if (val_c_pid != null && !val_c_pid.isNull()) {
            this.pid = (int)val_c_pid.asInt64();
            addField(FIELD_ID_PID);
        }

        JsonNode val_c_probeCount = inputJsonNode.get("probeCount");
        if (val_c_probeCount != null && !val_c_probeCount.isNull()) {
            this.probeCount = val_c_probeCount.asInt64();
            addField(FIELD_ID_PROBECOUNT);
        }

        JsonNode val_c_serverCurrentMillis = inputJsonNode.get("serverCurrentMillis");
        if (val_c_serverCurrentMillis != null && !val_c_serverCurrentMillis.isNull()) {
            this.serverCurrentMillis = val_c_serverCurrentMillis.asInt64();
            addField(FIELD_ID_SERVERCURRENTMILLIS);
        }

        JsonNode val_c_lastActiveMillis = inputJsonNode.get("lastActiveMillis");
        if (val_c_lastActiveMillis != null && !val_c_lastActiveMillis.isNull()) {
            this.lastActiveMillis = val_c_lastActiveMillis.asInt64();
            addField(FIELD_ID_LASTACTIVEMILLIS);
        }

        JsonNode val_c_options = inputJsonNode.get("options");
        if (val_c_options != null && !val_c_options.isNull()) {
            this.getOptions().defreezeFromJSON(val_c_options);
            addField(FIELD_ID_OPTIONS);
        }
    }
}

