// Java file generated automatically from `autogen.fzdl'.
// $Timestamp: 2018-11-28 18:08:43
// DO NOT EDIT THIS FILE UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING.
//
package gtcloud.common.cynosure.pdo;

import platon.ByteStream;
import platon.DefreezeException;
import platon.Freezable;
import platon.FreezerJSON;
import platon.FreezeException;
import platon.JsonNode;
import platon.Message;

public class ProbeAckDO extends Message implements FreezerJSON
{
    public static final int FIELD_ID_MAGICNUMBER = 0;
    public static final int FIELD_ID_SERVEREPOCH = 2;
    public static final int FIELD_ID_SERVERADDRESS = 1;
    public static final int FIELD_ID_OPTIONS = 3;

    private int magicNumber = 20181121;
    private long serverEpoch = 0;
    private String serverAddress = null;
    private platon.PropSet options = null;

    public ProbeAckDO() {
        addField(FIELD_ID_MAGICNUMBER);
        addField(FIELD_ID_SERVEREPOCH);
        addField(FIELD_ID_SERVERADDRESS);
        if (this.options != null) {
            addField(FIELD_ID_OPTIONS);
        }
    }

    public ProbeAckDO(ProbeAckDO other) {
        this.copyFrom(other);
    }

    public int getMagicNumber() {
        return this.magicNumber;
    }

    public void setMagicNumber(int val) {
        this.magicNumber = val;
    }

    public long getServerEpoch() {
        return this.serverEpoch;
    }

    public void setServerEpoch(long val) {
        this.serverEpoch = val;
    }

    public String getServerAddress() {
        return this.serverAddress;
    }

    public void setServerAddress(String val) {
        this.serverAddress = val;
    }

    public platon.PropSet getOptions() {
        if (this.options == null) {
            this.options = new platon.PropSet();
            this.addField(FIELD_ID_OPTIONS);
        }
        return this.options;
    }


    // 从给定对象拷贝数据到当前对象
    @Override
    public void copyFrom(Freezable other) {
        super.copyFrom(other);
        ProbeAckDO from = (ProbeAckDO)other;
        this.magicNumber = from.magicNumber;
        this.serverEpoch = from.serverEpoch;
        this.serverAddress = from.serverAddress;
        if (this.options == null) {
            this.options = new platon.PropSet();
        }
        this.options.copyFrom(from.getOptions());
    }

    // 克隆当前对象。
    @Override
    public Freezable makeClone() {
        ProbeAckDO o = new ProbeAckDO();
        o.copyFrom(this);
        return o;
    }

    public void clear() {
        this.magicNumber = 0;
        this.serverEpoch = 0;
        this.serverAddress = null;
        this.options = null;
        this.clearFields();
    }

    // 将当前对象打包进给定的字节流中。
    @Override
    public void freeze(ByteStream output) throws FreezeException {
        int[] cookie = new int[2];
        beginFreeze(output, cookie);

        if (hasField(FIELD_ID_MAGICNUMBER)) {
            writeFieldInt(output, FIELD_ID_MAGICNUMBER, this.magicNumber);
        }

        if (hasField(FIELD_ID_SERVEREPOCH)) {
            writeFieldLong(output, FIELD_ID_SERVEREPOCH, this.serverEpoch);
        }

        if (hasField(FIELD_ID_SERVERADDRESS)) {
            writeFieldString(output, FIELD_ID_SERVERADDRESS, this.serverAddress);
        }

        if (hasField(FIELD_ID_OPTIONS)) {
            writeFieldObject(output, FIELD_ID_OPTIONS, this.options);
        }

        endFreeze(output, cookie);
    }

    // 从给定字节流中解包, 并将解包得到的数据覆盖到当前对象上。
    @Override
    public void defreeze(ByteStream input) throws DefreezeException {
        clear();

        int messageLen = beginDefreeze(input);
        int lastPos = input.read_pos();
        while (messageLen > 0) {
            int[] tuple = readTag(input);
            int tagType = tuple[0];
            int fieldId = tuple[1];

            boolean consumed = false;
            switch (fieldId) {
            case FIELD_ID_MAGICNUMBER:
                if (tagType == TAG_TYPE_VARINT32) {
                    this.magicNumber = readFieldInt(input);
                    addField(FIELD_ID_MAGICNUMBER);
                    consumed = true;
                }
                break;

            case FIELD_ID_SERVEREPOCH:
                if (tagType == TAG_TYPE_FIXED64) {
                    this.serverEpoch = readFieldLong(input);
                    addField(FIELD_ID_SERVEREPOCH);
                    consumed = true;
                }
                break;

            case FIELD_ID_SERVERADDRESS:
                if (tagType == TAG_TYPE_LEN_PREFIXED) {
                    this.serverAddress = readFieldString(input);
                    addField(FIELD_ID_SERVERADDRESS);
                    consumed = true;
                }
                break;

            case FIELD_ID_OPTIONS:
                if (tagType == TAG_TYPE_EMBEDDEDMSG) {
                    if (this.options == null) {
                        this.options = new platon.PropSet();
                    }
                    readFieldObject(input, this.options);
                    addField(FIELD_ID_OPTIONS);
                    consumed = true;
                }
                break;
            }

            if (!consumed) {
                // unknown field, ignore it
                discardBytes(input, tagType);
            }

            final int currentPos = input.read_pos();
            messageLen -= (currentPos - lastPos);
            lastPos = currentPos;
        }

        endDefreeze(input);
    }

    // 将当前消息打包成JSON树, 返回JSON树的指针
    @Override
    public JsonNode freezeToJSON() throws FreezeException {
        JsonNode thisNode = JsonNode.createJsonObject();

        if (hasField(FIELD_ID_MAGICNUMBER)) {
            JsonNode val_c_magicNumber = new JsonNode(this.magicNumber);
            thisNode.put("magicNumber", val_c_magicNumber);
        }

        if (hasField(FIELD_ID_SERVEREPOCH)) {
            JsonNode val_c_serverEpoch = new JsonNode(this.serverEpoch);
            thisNode.put("serverEpoch", val_c_serverEpoch);
        }

        if (hasField(FIELD_ID_SERVERADDRESS) && this.serverAddress != null) {
            JsonNode val_c_serverAddress = new JsonNode(this.serverAddress);
            thisNode.put("serverAddress", val_c_serverAddress);
        }

        if (hasField(FIELD_ID_OPTIONS) && this.options != null) {
            JsonNode val_c_options = this.options.freezeToJSON();
            thisNode.put("options", val_c_options);
        }
        return thisNode;
    }

    // 从给定JSON树中解包, 并将解包得到的数据覆盖到当前消息上。
    @Override
    public void defreezeFromJSON(JsonNode inputJsonNode) throws DefreezeException {
        if (!inputJsonNode.isObject()) {
            throw new DefreezeException("input json is not object");
        }
        clear();

        JsonNode val_c_magicNumber = inputJsonNode.get("magicNumber");
        if (val_c_magicNumber != null && !val_c_magicNumber.isNull()) {
            this.magicNumber = (int)val_c_magicNumber.asInt64();
            addField(FIELD_ID_MAGICNUMBER);
        }

        JsonNode val_c_serverEpoch = inputJsonNode.get("serverEpoch");
        if (val_c_serverEpoch != null && !val_c_serverEpoch.isNull()) {
            this.serverEpoch = val_c_serverEpoch.asInt64();
            addField(FIELD_ID_SERVEREPOCH);
        }

        JsonNode val_c_serverAddress = inputJsonNode.get("serverAddress");
        if (val_c_serverAddress != null && !val_c_serverAddress.isNull()) {
            this.serverAddress = val_c_serverAddress.asString();
            addField(FIELD_ID_SERVERADDRESS);
        }

        JsonNode val_c_options = inputJsonNode.get("options");
        if (val_c_options != null && !val_c_options.isNull()) {
            this.getOptions().defreezeFromJSON(val_c_options);
            addField(FIELD_ID_OPTIONS);
        }
    }
}

