// Java file generated automatically from `autogen.fzdl'.
// $Timestamp: 2018-11-28 18:08:44
// DO NOT EDIT THIS FILE UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING.
//
package gtcloud.common.cynosure.pdo;

import platon.ByteStream;
import platon.DefreezeException;
import platon.Freezable;
import platon.FreezerJSON;
import platon.FreezeException;
import platon.JsonNode;
import platon.Message;

public class ResultDO extends Message implements FreezerJSON
{
    public static final int FIELD_ID_STATUSCODE = 0;
    public static final int FIELD_ID_STATUSMESSAGE = 1;

    private int statusCode = 0;
    private String statusMessage = "OK";

    public ResultDO() {
        addField(FIELD_ID_STATUSCODE);
        addField(FIELD_ID_STATUSMESSAGE);
    }

    public ResultDO(ResultDO other) {
        this.copyFrom(other);
    }

    public int getStatusCode() {
        return this.statusCode;
    }

    public void setStatusCode(int val) {
        this.statusCode = val;
    }

    public String getStatusMessage() {
        return this.statusMessage;
    }

    public void setStatusMessage(String val) {
        this.statusMessage = val;
    }


    // 从给定对象拷贝数据到当前对象
    @Override
    public void copyFrom(Freezable other) {
        super.copyFrom(other);
        ResultDO from = (ResultDO)other;
        this.statusCode = from.statusCode;
        this.statusMessage = from.statusMessage;
    }

    // 克隆当前对象。
    @Override
    public Freezable makeClone() {
        ResultDO o = new ResultDO();
        o.copyFrom(this);
        return o;
    }

    public void clear() {
        this.statusCode = 0;
        this.statusMessage = null;
        this.clearFields();
    }

    // 将当前对象打包进给定的字节流中。
    @Override
    public void freeze(ByteStream output) throws FreezeException {
        int[] cookie = new int[2];
        beginFreeze(output, cookie);

        if (hasField(FIELD_ID_STATUSCODE)) {
            writeFieldInt(output, FIELD_ID_STATUSCODE, this.statusCode);
        }

        if (hasField(FIELD_ID_STATUSMESSAGE)) {
            writeFieldString(output, FIELD_ID_STATUSMESSAGE, this.statusMessage);
        }

        endFreeze(output, cookie);
    }

    // 从给定字节流中解包, 并将解包得到的数据覆盖到当前对象上。
    @Override
    public void defreeze(ByteStream input) throws DefreezeException {
        clear();

        int messageLen = beginDefreeze(input);
        int lastPos = input.read_pos();
        while (messageLen > 0) {
            int[] tuple = readTag(input);
            int tagType = tuple[0];
            int fieldId = tuple[1];

            boolean consumed = false;
            switch (fieldId) {
            case FIELD_ID_STATUSCODE:
                if (tagType == TAG_TYPE_VARINT32) {
                    this.statusCode = readFieldInt(input);
                    addField(FIELD_ID_STATUSCODE);
                    consumed = true;
                }
                break;

            case FIELD_ID_STATUSMESSAGE:
                if (tagType == TAG_TYPE_LEN_PREFIXED) {
                    this.statusMessage = readFieldString(input);
                    addField(FIELD_ID_STATUSMESSAGE);
                    consumed = true;
                }
                break;
            }

            if (!consumed) {
                // unknown field, ignore it
                discardBytes(input, tagType);
            }

            final int currentPos = input.read_pos();
            messageLen -= (currentPos - lastPos);
            lastPos = currentPos;
        }

        endDefreeze(input);
    }

    // 将当前消息打包成JSON树, 返回JSON树的指针
    @Override
    public JsonNode freezeToJSON() throws FreezeException {
        JsonNode thisNode = JsonNode.createJsonObject();

        if (hasField(FIELD_ID_STATUSCODE)) {
            JsonNode val_c_statusCode = new JsonNode(this.statusCode);
            thisNode.put("statusCode", val_c_statusCode);
        }

        if (hasField(FIELD_ID_STATUSMESSAGE) && this.statusMessage != null) {
            JsonNode val_c_statusMessage = new JsonNode(this.statusMessage);
            thisNode.put("statusMessage", val_c_statusMessage);
        }
        return thisNode;
    }

    // 从给定JSON树中解包, 并将解包得到的数据覆盖到当前消息上。
    @Override
    public void defreezeFromJSON(JsonNode inputJsonNode) throws DefreezeException {
        if (!inputJsonNode.isObject()) {
            throw new DefreezeException("input json is not object");
        }
        clear();

        JsonNode val_c_statusCode = inputJsonNode.get("statusCode");
        if (val_c_statusCode != null && !val_c_statusCode.isNull()) {
            this.statusCode = (int)val_c_statusCode.asInt64();
            addField(FIELD_ID_STATUSCODE);
        }

        JsonNode val_c_statusMessage = inputJsonNode.get("statusMessage");
        if (val_c_statusMessage != null && !val_c_statusMessage.isNull()) {
            this.statusMessage = val_c_statusMessage.asString();
            addField(FIELD_ID_STATUSMESSAGE);
        }
    }
}

